version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "LorenceTest1"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-13p20wv4bb4c9"
s3_prefix = "LorenceTest1"
region = "ap-southeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
